export { SalesModule } from './SalesModule';
export { CollectModule } from './CollectModule';
export { AbsenceReportModule } from './AbsenceReportModule';
export { AbsenceApprovalModule } from './AbsenceApprovalModule';
export { TasksModule } from './TasksModule';
export { KpiDashboardModule } from './KpiDashboardModule';
export { ReportsModule } from './ReportsModule';
export { ShiftsModule } from './ShiftsModule';
export { PresenceModule } from './PresenceModule';
export { ChatModule } from './ChatModule';
export { EmailModule } from './EmailModule';
export { MotivationModule } from './MotivationModule';
export { MotivationProductsModule } from './MotivationProductsModule';
export { MODULE_REGISTRY, getModuleComponent } from './registry';
