// Auto-generated - 2026-01-29T21:52:47.144Z
// DO NOT EDIT MANUALLY - use admin interface to modify data

import { AttendanceRecord, Store, Role, User, AbsenceRequest, StoreOpeningHours } from '@/types';

// Mock stores
export const MOCK_STORES: Store[] = [
  { id: 'store-1', name: 'Bohnice', address: '', active: true },
  {
    id: 'store-2',
    name: 'Butovice',
    address: '',
    active: true,
    openingHours: {
      sameAllWeek: true,
      default: { open: '09:00', close: '21:00', closed: false },
    },
  },
  {
    id: 'store-3',
    name: 'Brno',
    address: '',
    active: true,
    openingHours: {
      sameAllWeek: true,
      default: { open: '10:00', close: '21:00', closed: false },
    },
  },
  { id: 'store-4', name: 'Č Most', address: '', active: true },
  {
    id: 'store-5',
    name: 'OC Šestka',
    address: '',
    active: true,
    openingHours: {
      sameAllWeek: true,
      default: { open: '09:00', close: '20:00', closed: false },
    },
  },
  {
    id: 'store-6',
    name: 'Prosek',
    address: '',
    active: true,
    openingHours: {
      sameAllWeek: false,
      monday: { open: '07:00', close: '20:00', closed: false },
      tuesday: { open: '07:00', close: '20:00', closed: false },
      wednesday: { open: '07:00', close: '20:00', closed: false },
      thursday: { open: '07:00', close: '20:00', closed: false },
      friday: { open: '07:00', close: '20:00', closed: false },
      saturday: { open: '08:30', close: '18:00', closed: false },
      sunday: { open: '08:30', close: '18:00', closed: false },
    },
  },
  {
    id: 'store-7',
    name: 'Ústí',
    address: '',
    active: true,
    openingHours: {
      sameAllWeek: true,
      default: { open: '08:00', close: '20:00', closed: false },
    },
  },
  {
    id: 'store-8',
    name: 'Chodov',
    address: '',
    active: true,
    openingHours: {
      sameAllWeek: true,
      default: { open: '09:00', close: '21:00', closed: false },
    },
  },
  {
    id: 'store-9',
    name: 'Vysočany',
    address: '',
    active: true,
    openingHours: {
      sameAllWeek: false,
      monday: { open: '09:00', close: '19:00', closed: false },
      tuesday: { open: '10:00', close: '18:00', closed: false },
      wednesday: { open: '09:00', close: '19:00', closed: false },
      thursday: { open: '09:00', close: '18:00', closed: false },
      friday: { open: '09:00', close: '18:00', closed: false },
      saturday: { open: '09:00', close: '14:00', closed: true },
      sunday: { open: '00:00', close: '00:00', closed: true },
    },
  },
  {
    id: 'store-10',
    name: 'Zličín',
    address: '',
    active: true,
    openingHours: {
      sameAllWeek: true,
      default: { open: '09:00', close: '21:00', closed: false },
    },
  },
];

// Mock roles (8 roles)
export const MOCK_ROLES: Role[] = [
  { id: 'role-1', name: 'Prodavač', type: 'prodavac', active: true },
  { id: 'role-2', name: 'Administrátor', type: 'administrator', active: true },
  { id: 'role-3', name: 'Skladník', type: 'skladnik', active: true },
  { id: 'role-4', name: 'Vedoucí skladu', type: 'vedouci-sklad', active: true },
  { id: 'role-5', name: 'Obsluha e-shopu', type: 'obsluha-eshop', active: true },
  { id: 'role-6', name: 'Obchodník', type: 'obchodnik', active: true },
  { id: 'role-7', name: 'Vedoucí velkoobchodu', type: 'vedouci-velkoobchod', active: true },
  { id: 'role-8', name: 'Majitel', type: 'majitel', active: true },
];

// Mock users (28 employees)
export const MOCK_USERS: User[] = [
  { id: 'user-1', username: 'pbures', fullName: 'Bureš Pavel', roleIds: ['role-3'], storeIds: [], active: true },
  { id: 'user-2', username: 'aburianova', fullName: 'Burianová Aneta', roleIds: ['role-1'], storeIds: ['store-7'], active: true, startsWithShortWeek: false },
  { id: 'user-3', username: 'mcapek', fullName: 'Čapek Michal', roleIds: ['role-3'], storeIds: [], active: true },
  { id: 'user-4', username: 'lferova', fullName: 'Férová Lucie', roleIds: ['role-5'], storeIds: [], active: true },
  { id: 'user-5', username: 'afratricova', fullName: 'Fratričová Alžbeta', roleIds: ['role-3'], storeIds: [], active: true },
  { id: 'user-6', username: 'khodek', fullName: 'Hodek Karel', roleIds: ['role-2'], storeIds: [], active: true },
  { id: 'user-7', username: 'dhysek', fullName: 'Hýsek David', roleIds: ['role-8'], storeIds: [], active: true },
  { id: 'user-8', username: 'ajindra', fullName: 'Jindra Aleš', roleIds: ['role-1'], storeIds: ['store-10'], active: true, startsWithShortWeek: false },
  { id: 'user-9', username: 'jkafagi', fullName: 'Kafagi Jakub', roleIds: ['role-5'], storeIds: [], active: true },
  { id: 'user-10', username: 'zkakur', fullName: 'Kakur Zdenko', roleIds: ['role-1'], storeIds: ['store-3'], active: true, startsWithShortWeek: false },
  { id: 'user-11', username: 'mkunik', fullName: 'Kunik Martin', roleIds: ['role-4'], storeIds: [], active: true },
  { id: 'user-12', username: 'hkuresova', fullName: 'Kurešová Hana', roleIds: ['role-1'], storeIds: ['store-6'], active: true, startsWithShortWeek: false },
  { id: 'user-13', username: 'jlhotak', fullName: 'Lhoták Jan', roleIds: ['role-7'], storeIds: [], active: true },
  { id: 'user-14', username: 'tlhotak', fullName: 'Lhoták Tomáš', roleIds: ['role-1', 'role-6'], storeIds: ['store-1', 'store-2', 'store-3', 'store-4', 'store-5', 'store-6', 'store-7', 'store-8', 'store-9', 'store-10'], defaultRoleId: 'role-6', defaultStoreId: 'store-1', active: true },
  { id: 'user-15', username: 'tlink', fullName: 'Link Tomáš', roleIds: ['role-1'], storeIds: ['store-5'], active: true, startsWithShortWeek: false },
  { id: 'user-16', username: 'kmarkova', fullName: 'Marková Kateřina', roleIds: ['role-1'], storeIds: ['store-2'], active: true, startsWithShortWeek: true },
  { id: 'user-17', username: 'mnadionova', fullName: 'Nadionová Markéta', roleIds: ['role-1'], storeIds: ['store-5'], active: true, startsWithShortWeek: false },
  { id: 'user-18', username: 'krabasova', fullName: 'Rabasová Kateřina', roleIds: ['role-1'], storeIds: ['store-7'], active: true, startsWithShortWeek: false },
  { id: 'user-19', username: 'vsmizansky', fullName: 'Smižanský Vilém', roleIds: ['role-5'], storeIds: [], active: true, workingHours: {
      sameAllWeek: false,
      monday: { open: '08:00', close: '16:30', closed: false },
      tuesday: { open: '08:00', close: '16:30', closed: false },
      wednesday: { open: '08:00', close: '16:30', closed: false },
      thursday: { open: '08:00', close: '16:30', closed: false },
      friday: { open: '08:00', close: '16:30', closed: false },
      saturday: { open: '08:00', close: '16:30', closed: true },
      sunday: { open: '08:00', close: '16:30', closed: true },
    } },
  { id: 'user-20', username: 'jsnasel', fullName: 'Snášel Jakub', roleIds: ['role-3'], storeIds: [], active: true },
  { id: 'user-21', username: 'osoucek', fullName: 'Souček Ondřej', roleIds: ['role-1'], storeIds: ['store-8'], active: true, startsWithShortWeek: false },
  { id: 'user-22', username: 'tstransky', fullName: 'Stránský Tadeáš', roleIds: ['role-1'], storeIds: ['store-3'], active: true, startsWithShortWeek: false },
  { id: 'user-23', username: 'vszkatul', fullName: 'Szkatuláková Věra', roleIds: ['role-1'], storeIds: ['store-6'], active: true, startsWithShortWeek: false },
  { id: 'user-24', username: 'zszolga', fullName: 'Szolga Zsolt', roleIds: ['role-1'], storeIds: ['store-9'], active: true, startsWithShortWeek: false },
  { id: 'user-25', username: 'lstepnickova', fullName: 'Štěpničková Lucie', roleIds: ['role-1'], storeIds: ['store-10'], active: true, startsWithShortWeek: false },
  { id: 'user-26', username: 'pbartunek', fullName: 'Bartůněk Petr', roleIds: ['role-1'], storeIds: ['store-2'], active: true, startsWithShortWeek: true },
  { id: 'user-27', username: 'pkot', fullName: 'Kot Patrícia', roleIds: ['role-1'], storeIds: ['store-1'], active: true, startsWithShortWeek: false },
  { id: 'user-4fcc693f-4f67-4a30-8bd8-9c50d140bd6c', username: 'mzizka', fullName: 'Žižka Michael', roleIds: ['role-1'], storeIds: ['store-8'], active: true, startsWithShortWeek: false },
];

// Mock attendance data (updated structure)
export const mockData: AttendanceRecord[] = [
  {
    date: '27. 01. 2024',
    store: 'Bohnice',
    workplaceType: 'store',
    workplaceId: 'store-1',
    workplaceName: 'Bohnice',
    user: 'Bureš Pavel',
    in: '08:00',
    out: '10:30',
    abs: 'Lékař',
    hrs: '2:30',
    absNote: 'Pravidelná kontrola u zubaře - ranní termín',
    cash: 4200,
    card: 3100,
    partner: 1500,
    flows: '+500',
    saleNote: 'Ranní doprodej skladových zásob',
    collected: false,
  },
  {
    date: '27. 01. 2024',
    store: 'Bohnice',
    workplaceType: 'store',
    workplaceId: 'store-1',
    workplaceName: 'Bohnice',
    user: 'Burianová Aneta',
    in: '10:30',
    out: '18:00',
    abs: '-',
    hrs: '7:30',
    absNote: '',
    cash: 6500,
    card: 4200,
    partner: 2100,
    flows: '-150',
    saleNote: 'Zástup za kolegu, terminál OK',
    collected: false,
  },
  {
    date: '26. 01. 2024',
    store: 'Brno',
    workplaceType: 'store',
    workplaceId: 'store-3',
    workplaceName: 'Brno',
    user: 'Čapek Michal',
    in: '09:00',
    out: '17:30',
    abs: '-',
    hrs: '8:30',
    absNote: '',
    cash: 12400,
    card: 8000,
    partner: 0,
    flows: '0',
    saleNote: 'Běžný provoz',
    collected: 'user-6',
  },
  {
    date: '25. 01. 2024',
    store: 'Chodov',
    workplaceType: 'store',
    workplaceId: 'store-8',
    workplaceName: 'Chodov',
    user: 'Férová Lucie',
    in: '08:00',
    out: '18:00',
    abs: '-',
    hrs: '10:00',
    absNote: '',
    cash: 11000,
    card: 9500,
    partner: 3000,
    flows: '+200',
    saleNote: 'Inventura OK',
    collected: false,
  },
];

// Legacy stores dropdown (for backwards compatibility)
export const stores = [
  { value: 'store-1', label: 'Prodejna Bohnice' },
  { value: 'store-2', label: 'Prodejna Butovice' },
  { value: 'store-3', label: 'Prodejna Brno' },
  { value: 'store-4', label: 'Prodejna Č Most' },
  { value: 'store-5', label: 'Prodejna OC Šestka' },
  { value: 'store-6', label: 'Prodejna Prosek' },
  { value: 'store-7', label: 'Prodejna Ústí' },
  { value: 'store-8', label: 'Prodejna Chodov' },
  { value: 'store-9', label: 'Prodejna Vysočany' },
  { value: 'store-10', label: 'Prodejna Zličín' },
];

// Admin stores dropdown
export const adminStores = [
  { value: 'all', label: 'VŠECHNY PRODEJNY' },
  { value: 'bohnice', label: 'BOHNICE' },
  { value: 'butovice', label: 'BUTOVICE' },
  { value: 'brno', label: 'BRNO' },
  { value: 'č most', label: 'Č MOST' },
  { value: 'oc šestka', label: 'OC ŠESTKA' },
  { value: 'prosek', label: 'PROSEK' },
  { value: 'ústí', label: 'ÚSTÍ' },
  { value: 'chodov', label: 'CHODOV' },
  { value: 'vysočany', label: 'VYSOČANY' },
  { value: 'zličín', label: 'ZLIČÍN' },
];

export const months = [
  { value: 'all', label: 'Měsíc: Vše' },
  { value: '01', label: 'Leden' },
  { value: '02', label: 'Únor' },
  { value: '03', label: 'Březen' },
  { value: '04', label: 'Duben' },
  { value: '05', label: 'Květen' },
  { value: '06', label: 'Červen' },
  { value: '07', label: 'Červenec' },
  { value: '08', label: 'Srpen' },
  { value: '09', label: 'Září' },
  { value: '10', label: 'Říjen' },
  { value: '11', label: 'Listopad' },
  { value: '12', label: 'Prosinec' },
];

function generateYears() {
  const currentYear = new Date().getFullYear();
  const years = [{ value: 'all', label: 'Rok: Vše' }];

  // Přidat aktuální rok a 2 roky zpět
  for (let year = currentYear; year >= currentYear - 2; year--) {
    years.push({ value: String(year), label: String(year) });
  }

  return years;
}

export const years = generateYears();

export const absenceTypes = [
  { value: 'Dovolená', label: 'Dovolená' },
  { value: 'Nemoc / Neschopenka', label: 'Nemoc / Neschopenka' },
  { value: 'Lékař', label: 'Lékař (v hodinách)' },
  { value: 'Neplacené volno', label: 'Neplacené volno' },
];

// Mock absence requests
export const MOCK_ABSENCE_REQUESTS: AbsenceRequest[] = [
  {
    id: 'abs-req-1',
    userId: 'user-7',
    type: 'Dovolená',
    dateFrom: '2025-02-10',
    dateTo: '2025-02-14',
    note: 'Rodinná dovolená',
    status: 'pending',
    createdAt: '2025-01-25T10:00:00Z',
  },
  {
    id: 'abs-req-2',
    userId: 'user-7',
    type: 'Lékař',
    dateFrom: '2025-01-30',
    dateTo: '2025-01-30',
    timeFrom: '08:00',
    timeTo: '10:00',
    note: 'Kontrola u zubaře',
    status: 'approved',
    createdAt: '2025-01-20T14:30:00Z',
    approvedBy: 'user-3',
    approvedAt: '2025-01-21T09:00:00Z',
    seenByUser: true,
  },
  {
    id: 'abs-req-3',
    userId: 'user-7',
    type: 'Neplacené volno',
    dateFrom: '2025-01-15',
    dateTo: '2025-01-15',
    note: 'Osobní záležitosti',
    status: 'rejected',
    createdAt: '2025-01-10T08:00:00Z',
    approvedBy: 'user-3',
    approvedAt: '2025-01-11T10:00:00Z',
    seenByUser: true,
  },
  {
    id: 'abs-req-4',
    userId: 'user-8',
    type: 'Nemoc / Neschopenka',
    dateFrom: '2025-01-28',
    dateTo: '2025-01-31',
    note: 'Chřipka',
    status: 'pending',
    createdAt: '2025-01-28T07:00:00Z',
  },
  {
    id: 'abs-req-5',
    userId: 'user-8',
    type: 'Dovolená',
    dateFrom: '2025-03-01',
    dateTo: '2025-03-07',
    note: 'Jarní prázdniny s dětmi',
    status: 'approved',
    createdAt: '2025-01-15T12:00:00Z',
    approvedBy: 'user-3',
    approvedAt: '2025-01-16T08:30:00Z',
    seenByUser: true,
  },
  {
    id: 'abs-req-6',
    userId: 'user-8',
    type: 'Lékař',
    dateFrom: '2025-02-05',
    dateTo: '2025-02-05',
    timeFrom: '14:00',
    timeTo: '16:00',
    note: 'Oční vyšetření',
    status: 'pending',
    createdAt: '2025-01-27T16:00:00Z',
  },
  {
    id: 'abs-req-7',
    userId: 'user-9',
    type: 'Dovolená',
    dateFrom: '2025-02-17',
    dateTo: '2025-02-21',
    note: 'Lyžování v Alpách',
    status: 'pending',
    createdAt: '2025-01-26T11:00:00Z',
  },
  {
    id: 'abs-req-8',
    userId: 'user-9',
    type: 'Lékař',
    dateFrom: '2025-01-29',
    dateTo: '2025-01-29',
    timeFrom: '09:00',
    timeTo: '11:30',
    note: 'Preventivní prohlídka',
    status: 'approved',
    createdAt: '2025-01-22T10:00:00Z',
    approvedBy: 'user-4',
    approvedAt: '2025-01-23T09:15:00Z',
    seenByUser: true,
  },
  {
    id: 'abs-req-9',
    userId: 'user-9',
    type: 'Neplacené volno',
    dateFrom: '2025-01-10',
    dateTo: '2025-01-10',
    note: 'Stěhování',
    status: 'rejected',
    createdAt: '2025-01-05T14:00:00Z',
    approvedBy: 'user-4',
    approvedAt: '2025-01-06T11:00:00Z',
    seenByUser: true,
  },
  {
    id: 'abs-req-10',
    userId: 'user-2',
    type: 'Dovolená',
    dateFrom: '2025-02-24',
    dateTo: '2025-02-28',
    note: 'Dovolená u moře',
    status: 'pending',
    createdAt: '2025-01-27T09:00:00Z',
  },
  {
    id: 'abs-req-11',
    userId: 'user-2',
    type: 'Nemoc / Neschopenka',
    dateFrom: '2025-01-20',
    dateTo: '2025-01-22',
    note: 'Viróza',
    status: 'approved',
    createdAt: '2025-01-20T06:30:00Z',
    approvedBy: 'user-4',
    approvedAt: '2025-01-20T08:00:00Z',
    seenByUser: true,
  },
  {
    id: 'abs-req-12',
    userId: 'user-2',
    type: 'Lékař',
    dateFrom: '2025-02-03',
    dateTo: '2025-02-03',
    timeFrom: '10:00',
    timeTo: '12:00',
    note: 'Gynekologická prohlídka',
    status: 'approved',
    createdAt: '2025-01-28T15:00:00Z',
    approvedBy: 'user-13',
    approvedAt: '2026-01-29T18:22:17.408Z',
    seenByUser: false,
  },
  {
    id: 'abs-req-13',
    userId: 'user-10',
    type: 'Neplacené volno',
    dateFrom: '2025-02-07',
    dateTo: '2025-02-07',
    note: 'Vyřizování na úřadech',
    status: 'pending',
    createdAt: '2025-01-26T13:00:00Z',
  },
  {
    id: 'abs-req-14',
    userId: 'user-10',
    type: 'Dovolená',
    dateFrom: '2025-04-14',
    dateTo: '2025-04-18',
    note: 'Velikonoční dovolená',
    status: 'approved',
    createdAt: '2025-01-10T10:00:00Z',
    approvedBy: 'user-4',
    approvedAt: '2025-01-12T14:00:00Z',
    seenByUser: true,
  },
  {
    id: 'abs-req-15',
    userId: 'user-10',
    type: 'Lékař',
    dateFrom: '2025-01-08',
    dateTo: '2025-01-08',
    timeFrom: '15:00',
    timeTo: '16:30',
    note: 'Ortoped - bolest zad',
    status: 'rejected',
    createdAt: '2025-01-03T11:00:00Z',
    approvedBy: 'user-4',
    approvedAt: '2025-01-04T09:00:00Z',
    seenByUser: true,
  },
  {
    id: 'abs-req-16',
    userId: 'user-3',
    type: 'Dovolená',
    dateFrom: '2025-03-10',
    dateTo: '2025-03-14',
    note: 'Rodinná dovolená',
    status: 'pending',
    createdAt: '2025-01-28T10:00:00Z',
  },
  {
    id: 'abs-req-17',
    userId: 'user-3',
    type: 'Lékař',
    dateFrom: '2025-02-12',
    dateTo: '2025-02-12',
    timeFrom: '08:00',
    timeTo: '09:30',
    note: 'Odběr krve',
    status: 'approved',
    createdAt: '2025-01-20T09:00:00Z',
    approvedBy: 'user-1',
    approvedAt: '2025-01-21T08:00:00Z',
    seenByUser: true,
  },
  {
    id: 'abs-req-18',
    userId: 'user-3',
    type: 'Nemoc / Neschopenka',
    dateFrom: '2025-01-06',
    dateTo: '2025-01-08',
    note: 'Angína',
    status: 'approved',
    createdAt: '2025-01-06T07:00:00Z',
    approvedBy: 'user-1',
    approvedAt: '2025-01-06T08:30:00Z',
    seenByUser: true,
  },
  {
    id: 'abs-req-19',
    userId: 'user-4',
    type: 'Dovolená',
    dateFrom: '2025-04-07',
    dateTo: '2025-04-11',
    note: 'Jarní dovolená',
    status: 'pending',
    createdAt: '2025-01-27T14:00:00Z',
  },
  {
    id: 'abs-req-20',
    userId: 'user-4',
    type: 'Lékař',
    dateFrom: '2025-02-06',
    dateTo: '2025-02-06',
    timeFrom: '13:00',
    timeTo: '15:00',
    note: 'Zubař - plomba',
    status: 'approved',
    createdAt: '2025-01-18T11:00:00Z',
    approvedBy: 'user-6',
    approvedAt: '2025-01-19T10:00:00Z',
    seenByUser: true,
  },
  {
    id: 'abs-req-21',
    userId: 'user-4',
    type: 'Neplacené volno',
    dateFrom: '2025-01-03',
    dateTo: '2025-01-03',
    note: 'Osobní důvody',
    status: 'rejected',
    createdAt: '2024-12-28T10:00:00Z',
    approvedBy: 'user-1',
    approvedAt: '2024-12-30T09:00:00Z',
    seenByUser: true,
  },
];
