import { AttendanceRecord, Store, Role, User } from '@/types';

// Mock stores
export const MOCK_STORES: Store[] = [
  { id: 'store-1', name: 'Bohnice', address: '', active: true },
  { id: 'store-2', name: 'Butovice', address: '', active: true },
  { id: 'store-3', name: 'Brno', address: '', active: true },
  { id: 'store-4', name: 'Č Most', address: '', active: true },
  { id: 'store-5', name: 'OC Šestka', address: '', active: true },
  { id: 'store-6', name: 'Prosek', address: '', active: true },
  { id: 'store-7', name: 'Ústí', address: '', active: true },
  { id: 'store-8', name: 'Chodov', address: '', active: true },
  { id: 'store-9', name: 'Vysočany', address: '', active: true },
  { id: 'store-10', name: 'Zličín', address: '', active: true },
];

// Mock roles (8 roles)
export const MOCK_ROLES: Role[] = [
  { id: 'role-1', name: 'Prodavač', type: 'prodavac', active: true },
  { id: 'role-2', name: 'Administrátor', type: 'administrator', active: true },
  { id: 'role-3', name: 'Skladník', type: 'skladnik', active: true },
  { id: 'role-4', name: 'Vedoucí skladu', type: 'vedouci-sklad', active: true },
  { id: 'role-5', name: 'Obsluha e-shopu', type: 'obsluha-eshop', active: true },
  { id: 'role-6', name: 'Obchodník', type: 'obchodnik', active: true },
  { id: 'role-7', name: 'Vedoucí velkoobchodu', type: 'vedouci-velkoobchod', active: true },
  { id: 'role-8', name: 'Majitel', type: 'majitel', active: true },
];

// Mock users (27 employees)
export const MOCK_USERS: User[] = [
  { id: 'user-1', username: 'pbures', fullName: 'Bureš Pavel', roleIds: ['role-1', 'role-2'], storeIds: [], active: true },
  { id: 'user-2', username: 'aburianova', fullName: 'Burianová Aneta', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-3', username: 'mcapek', fullName: 'Čapek Michal', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-4', username: 'lferova', fullName: 'Férová Lucie', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-5', username: 'afratricova', fullName: 'Fratričová Alžbeta', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-6', username: 'khodek', fullName: 'Hodek Karel', roleIds: ['role-1', 'role-2'], storeIds: [], active: true },
  { id: 'user-7', username: 'dhysek', fullName: 'Hýsek David', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-8', username: 'ajindra', fullName: 'Jindra Aleš', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-9', username: 'jkafagi', fullName: 'Kafagi Jakub', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-10', username: 'zkakur', fullName: 'Kakur Zdenko', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-11', username: 'mkunik', fullName: 'Kunik Martin', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-12', username: 'hkuresova', fullName: 'Kurešová Hana', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-13', username: 'jlhotak', fullName: 'Lhoták Jan', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-14', username: 'tlhotak', fullName: 'Lhoták Tomáš', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-15', username: 'tlink', fullName: 'Link Tomáš', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-16', username: 'kmarkova', fullName: 'Marková Kateřina', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-17', username: 'mnadionova', fullName: 'Nadionová Markéta', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-18', username: 'krabasova', fullName: 'Rabasová Kateřina', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-19', username: 'vsmizansky', fullName: 'Smižanský Vilém', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-20', username: 'jsnasel', fullName: 'Snášel Jakub', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-21', username: 'osoucek', fullName: 'Souček Ondřej', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-22', username: 'tstransky', fullName: 'Stránský Tadeáš', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-23', username: 'vszkatul', fullName: 'Szkatuláková Věra', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-24', username: 'zszolga', fullName: 'Szolga Zsolt', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-25', username: 'lstepnickova', fullName: 'Štěpničková Lucie', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-26', username: 'pbartunek', fullName: 'Bartůněk Petr', roleIds: ['role-1'], storeIds: [], active: true },
  { id: 'user-27', username: 'pkot', fullName: 'Kot Patrícia', roleIds: ['role-1'], storeIds: [], active: true },
];

// Mock attendance data (updated structure)
export const mockData: AttendanceRecord[] = [
  {
    date: '27. 01. 2024',
    store: 'Bohnice',
    workplaceType: 'store',
    workplaceId: 'store-1',
    workplaceName: 'Bohnice',
    user: 'Bureš Pavel',
    in: '08:00',
    out: '10:30',
    abs: 'Lékař',
    hrs: '2:30',
    absNote: 'Pravidelná kontrola u zubaře - ranní termín',
    cash: 4200,
    card: 3100,
    partner: 1500,
    flows: '+500',
    saleNote: 'Ranní doprodej skladových zásob',
    collected: false,
  },
  {
    date: '27. 01. 2024',
    store: 'Bohnice',
    workplaceType: 'store',
    workplaceId: 'store-1',
    workplaceName: 'Bohnice',
    user: 'Burianová Aneta',
    in: '10:30',
    out: '18:00',
    abs: '-',
    hrs: '7:30',
    absNote: '',
    cash: 6500,
    card: 4200,
    partner: 2100,
    flows: '-150',
    saleNote: 'Zástup za kolegu, terminál OK',
    collected: false,
  },
  {
    date: '26. 01. 2024',
    store: 'Brno',
    workplaceType: 'store',
    workplaceId: 'store-3',
    workplaceName: 'Brno',
    user: 'Čapek Michal',
    in: '09:00',
    out: '17:30',
    abs: '-',
    hrs: '8:30',
    absNote: '',
    cash: 12400,
    card: 8000,
    partner: 0,
    flows: '0',
    saleNote: 'Běžný provoz',
    collected: 'Hodek Karel',
  },
  {
    date: '25. 01. 2024',
    store: 'Chodov',
    workplaceType: 'store',
    workplaceId: 'store-8',
    workplaceName: 'Chodov',
    user: 'Férová Lucie',
    in: '08:00',
    out: '18:00',
    abs: '-',
    hrs: '10:00',
    absNote: '',
    cash: 11000,
    card: 9500,
    partner: 3000,
    flows: '+200',
    saleNote: 'Inventura OK',
    collected: false,
  },
];

// Legacy stores dropdown (for backwards compatibility)
export const stores = [
  { value: 'store-1', label: 'Prodejna Bohnice' },
  { value: 'store-2', label: 'Prodejna Butovice' },
  { value: 'store-3', label: 'Prodejna Brno' },
  { value: 'store-4', label: 'Prodejna Č Most' },
  { value: 'store-5', label: 'Prodejna OC Šestka' },
  { value: 'store-6', label: 'Prodejna Prosek' },
  { value: 'store-7', label: 'Prodejna Ústí' },
  { value: 'store-8', label: 'Prodejna Chodov' },
  { value: 'store-9', label: 'Prodejna Vysočany' },
  { value: 'store-10', label: 'Prodejna Zličín' },
];

// Admin stores dropdown
export const adminStores = [
  { value: 'all', label: 'VŠECHNY PRODEJNY' },
  { value: 'bohnice', label: 'BOHNICE' },
  { value: 'butovice', label: 'BUTOVICE' },
  { value: 'brno', label: 'BRNO' },
  { value: 'c most', label: 'Č MOST' },
  { value: 'oc sestka', label: 'OC ŠESTKA' },
  { value: 'prosek', label: 'PROSEK' },
  { value: 'usti', label: 'ÚSTÍ' },
  { value: 'chodov', label: 'CHODOV' },
  { value: 'vysocany', label: 'VYSOČANY' },
  { value: 'zlicin', label: 'ZLIČÍN' },
];

export const months = [
  { value: 'all', label: 'Měsíc: Vše' },
  { value: '01', label: 'Leden' },
  { value: '02', label: 'Únor' },
  { value: '03', label: 'Březen' },
  { value: '04', label: 'Duben' },
  { value: '05', label: 'Květen' },
  { value: '06', label: 'Červen' },
  { value: '07', label: 'Červenec' },
  { value: '08', label: 'Srpen' },
  { value: '09', label: 'Září' },
  { value: '10', label: 'Říjen' },
  { value: '11', label: 'Listopad' },
  { value: '12', label: 'Prosinec' },
];

export const years = [
  { value: 'all', label: 'Rok: Vše' },
  { value: '2024', label: '2024' },
  { value: '2025', label: '2025' },
];

export const absenceTypes = [
  { value: 'Dovolená', label: 'Dovolená' },
  { value: 'Nemoc / Neschopenka', label: 'Nemoc / Neschopenka' },
  { value: 'Lékař', label: 'Lékař (v hodinách)' },
  { value: 'Neplacené volno', label: 'Neplacené volno' },
];
